/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sign_jni_Jni */

#ifndef _Included_sign_jni_Jni
#define _Included_sign_jni_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sign_jni_Jni
 * Method:    getInfoMD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sign_jni_Jni_getInfoMD5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
